services:
  tasks-to-ical:
    build: ./
    container_name: tasks_to_ical
    env_file:
      - .env
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - ./credentials.json:/tasks-to-ical/credentials.json
      - ./token.json:/tasks-to-ical/token.json
    ports:
      - 9799:8080
    restart: unless-stopped
